# Generated by Django 2.2.6 on 2019-11-01 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0002_auto_20191101_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='columns', to='columns.ColumnType'),
        ),
    ]
