# Generated by Django 2.2.6 on 2019-11-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0003_auto_20191101_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnOptionTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=80, unique=True)),
                ('detail', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='columntype',
            name='detail',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='columntype',
            name='display_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='columntype',
            name='value',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
