# Generated by Django 2.2.6 on 2019-11-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0005_auto_20191101_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnoptiontype',
            name='chioces',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
